image: mcr.microsoft.com/dotnet/sdk:9.0 # Або 8.0, як обговорювалося раніше, якщо 9.0 не є строгою вимогою

variables:
  GIT_STRATEGY: clone # Можна спробувати 'fetch', якщо 'clone' постійно не вдається
  GIT_TRACE: "true"   # Вмикає детальне логування команд Git
  GIT_CURL_VERBOSE: "true" # Вмикає детальне логування для HTTP-операцій Git
  # Шляхи до файлів проектів відносно кореня репозиторію
  SOLUTION_FILE: "Assessment.sln"
  SESSION_MVC_PROJECT_PATH: "SessionMVC/SessionMVC.csproj"
  TEST_PROJECT_PATH: "Session.UnitTests/Session.UnitTests.csproj"

stages:
  - build
  - test

before_script:
  - echo "Using .NET SDK $(dotnet --version)"
  - dotnet --info
  - echo "Attempting to clone from $CI_REPOSITORY_URL" # Ця змінна містить URL, який використовується для клонування

build_solution:
  stage: build
  script:
    - echo "Restoring NuGet packages for solution ${SOLUTION_FILE}..."
    - dotnet restore "${SOLUTION_FILE}"
    - echo "Building solution ${SOLUTION_FILE} in Release configuration..."
    - dotnet build "${SOLUTION_FILE}" --configuration Release --no-restore
  artifacts:
    paths:
      - sessionMVC/bin/Release/net9.0/
      # - sessionMVC/obj/Release/net9.0/
    expire_in: 1 hour

run_tests:
  stage: test
  needs: [build_solution]
  script:
    - echo "Running tests for ${TEST_PROJECT_PATH}..."
    - dotnet test "${TEST_PROJECT_PATH}" --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
  artifacts:
    when: always
    reports:
      junit: "${TEST_PROJECT_PATH}/TestResults/test_results.trx"