image: mcr.microsoft.com/dotnet/sdk:9.0

variables:
  GIT_STRATEGY: clone
  GIT_TRACE: "true"
  GIT_CURL_VERBOSE: "true"
  SOLUTION_FILE: "Assessment.sln"
  SESSION_MVC_DIR: "SessionMVC"
  TEST_PROJECT_DIR: "Session.UnitTests"
  TEST_PROJECT_CSPROJ_PATH: "${TEST_PROJECT_DIR}/Session.UnitTests.csproj"

stages:
  - build
  # - test # Тимчасово вимкнемо тести для простоти

before_script:
  - echo "Using .NET SDK $(dotnet --version)"
  - dotnet --info
  # - echo "Attempting to clone from $CI_REPOSITORY_URL" # Клонування зараз не головне для цього тесту

build_solution: # Назва залишається, але суть змінюється для тесту
  stage: build
  script:
    - echo "This is a test artifact content" > my_simple_artifact.txt
    - echo "Test artifact created."
    - ls -l my_simple_artifact.txt # Перевіряємо, чи файл створено
  artifacts:
    paths:
      - my_simple_artifact.txt # Завантажуємо тільки цей простий файл
    expire_in: 1 hour

# run_tests: # Тимчасово вимкнемо етап тестів
#   stage: test
#   needs: [build_solution]
#   script:
#     - echo "Running tests for ${TEST_PROJECT_CSPROJ_PATH}..."
#     - dotnet test "${TEST_PROJECT_CSPROJ_PATH}" --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
#   artifacts:
#     when: always
#     reports:
#       junit: "${TEST_PROJECT_DIR}/TestResults/test_results.trx"