services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Your_password123" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - devnetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123 -N -C -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    
  rabbitmq:
    image: rabbitmq:3.12-management 
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s 
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5552:5552" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      - devnetwork
    restart: unless-stopped

  mongo:
    image: mongo:7.0 
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: example 
    volumes:
      - mongo_data:/data/db 
    healthcheck:
      # Виправлено: mongosh має бути доступний, якщо базовий образ mongo його містить.
      # Якщо ні, можна використовувати mongo shell або інший метод перевірки.
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devnetwork
    
  sessionmvc:
    image: sessionmvc 
    build:
      context: .
      dockerfile: Dockerfile # Оскільки Dockerfile тепер у корені
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      # ASPNETCORE_HTTP_PORTS=5000 # Встановлюється у Dockerfile
      - ConnectionStrings__AssessmentDbConnectionString=Server=db;Database=Assessment;User=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True
      - MongoConnectionString=mongodb://mongo:27017/Assessment?directConnection=true # Переконайтеся, що 'Assessment' - правильна назва БД
    ports:
      - "8081:5000" 
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - devnetwork
    restart: unless-stopped

volumes:
  sqlvolume:
  rabbitmq_data:
  mongo_data:
    
networks:
  devnetwork:
    driver: bridge
